const data = {
    products: [
        {
            _id:'1',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Adidas Shirt',
            category:'Shirts',
            image:'/images/p2.jpg',
            price:80,
            brand:'Adidas',
            rating:4.0,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'UA Shirt',
            category:'Shirts',
            image:'/images/p3.jpg',
            price:100,
            brand:'Under Armour',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Nike Shorts',
            category:'Pants',
            image:'/images/p4.jpg',
            price:80,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Adidas Shorts',
            category:'Pants',
            image:'/images/p5.jpg',
            price:70,
            brand:'Adidas',
            rating:4.0,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'UA Shorts',
            category:'Pants',
            image:'/images/p6.jpg',
            price:90,
            brand:'Under Armour',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
    ],
};

export default data;